// Tailwind-based table styles
export const tableClasses = {
  table: 'w-full border-collapse border-spacing-0 px-2',
  thead: 'bg-gray-50',
  tbody: 'divide-y divide-gray-200',
  tr: 'hover:bg-gray-50 transition-colors',
  trSelected: 'bg-blue-50 border-blue-200 shadow-sm',
  th: 'px-4 py-3 text-left text-sm font-medium text-gray-900 uppercase tracking-wider border-b border-gray-200 bg-gray-50',
  thNumeric: 'text-right',
  td: 'px-4 py-3 text-sm text-gray-900 border-b border-gray-100',
  tdNumeric: 'text-right',
  tdFirst: 'rounded-l-md',
  tdLast: 'rounded-r-md',
  pagination: 'flex items-center justify-between bg-white px-4 py-3 border-t border-gray-200',
  paginationInfo: 'flex items-center text-sm text-gray-700',
  paginationControls: 'flex items-center space-x-2',
  button: 'inline-flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 hover:text-gray-700 disabled:opacity-50 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500',
  buttonActive: 'bg-blue-600 text-white border-blue-600 hover:bg-blue-700',
  buttonIcon: 'w-4 h-4',
  loader: 'flex items-center justify-center py-8 w-full',
  emptyState: 'text-center py-8 text-gray-500',
  sortIcon: 'ml-2 w-4 h-4',
  tooltip: 'relative inline-block',
  tooltipContent: 'absolute bottom-full left-1/2 transform -translate-x-1/2 mb-2 px-2 py-1 text-xs text-white bg-gray-800 rounded shadow-lg opacity-0 invisible transition-opacity duration-200 z-10',
  columnVisibility: 'relative inline-block',
  columnVisibilityButton: 'inline-flex items-center px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500',
  columnVisibilityMenu: 'absolute right-0 mt-2 w-48 bg-white border border-gray-200 rounded-md shadow-lg z-10',
  columnVisibilityItem: 'px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 cursor-pointer flex items-center',
  checkbox: 'w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500'
}